# Generated by Django 4.2.6 on 2024-02-16 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdf_files/')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='extracted_images/')),
                ('pdf_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_processor.pdfdocument')),
            ],
        ),
    ]
