# Generated by Django 4.2.6 on 2024-03-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0002_alter_extractedline_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedline',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
